# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alpha.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 589)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("* {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #101010;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px;\n"
"     background: white;\n"
"     height: 15px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: #b3b3b3;\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid rgb(1, 116, 101);\n"
"      border-radius: 2px;\n"
"      background: rgb(1, 116, 101);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid rgb(1, 116, 101);\n"
"      border-radius: 2px;\n"
"      background: rgb(1, 116, 101);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid white;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: white;\n"
"      width: 15px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: #b3b3b3;\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid rgb(1, 116, 101);\n"
"      border-radius: 2px;\n"
"      background: rgb(1, 116, 101);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid rgb(1, 116, 101);\n"
"      border-radius: 2px;\n"
"      background: rgb(1, 116, 101);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid white;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QMessageBox * {\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QMessageBox QPushButton{\n"
"    font-weight: bold;\n"
"    color: #ffffff;\n"
"    background-color: rgb(1, 116, 101);\n"
"    border: 1px solid #000000;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    width: 100px;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMessageBox QPushButton:hover{\n"
"    color: #000000;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QMessageBox QPushButton:pressed{\n"
"    color: #000000;\n"
"    background-color: #f2f2f2;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #101010;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setToolTip("")
        self.stackedWidget.setStyleSheet("background-color: #262626;\n"
"color: rgb(255, 255, 255);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.cameraViewPage = QtWidgets.QWidget()
        self.cameraViewPage.setStyleSheet("background-color: #262626;")
        self.cameraViewPage.setObjectName("cameraViewPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cameraViewPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mdiArea = QtWidgets.QMdiArea(self.cameraViewPage)
        self.mdiArea.setStyleSheet("background-color: #262626;\n"
"color: rgb(255, 255, 255);")
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout_2.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.cameraViewPage)
        self.videoGalleryPage = QtWidgets.QWidget()
        self.videoGalleryPage.setObjectName("videoGalleryPage")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.videoGalleryPage)
        self.gridLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.currentVideoGroupBox = QtWidgets.QGroupBox(self.videoGalleryPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.currentVideoGroupBox.setFont(font)
        self.currentVideoGroupBox.setStyleSheet("background-color: #333333;\n"
"border: 1px solid #333333;\n"
"border-top: 10px solid #333333;")
        self.currentVideoGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.currentVideoGroupBox.setObjectName("currentVideoGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.currentVideoGroupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 1, 1, 1)
        self.currentVideoLabel = QtWidgets.QLabel(self.currentVideoGroupBox)
        self.currentVideoLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.currentVideoLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.currentVideoLabel.setStyleSheet("background-color: #333333;")
        self.currentVideoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.currentVideoLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentVideoLabel.setText("")
        self.currentVideoLabel.setScaledContents(True)
        self.currentVideoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentVideoLabel.setWordWrap(False)
        self.currentVideoLabel.setObjectName("currentVideoLabel")
        self.gridLayout_10.addWidget(self.currentVideoLabel, 0, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.currentVideoGroupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.playVideoButton = QtWidgets.QPushButton(self.frame_2)
        self.playVideoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playVideoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.playVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.playVideoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playVideoButton.setIcon(icon)
        self.playVideoButton.setIconSize(QtCore.QSize(30, 30))
        self.playVideoButton.setObjectName("playVideoButton")
        self.verticalLayout_2.addWidget(self.playVideoButton)
        self.analyseVideoButton = QtWidgets.QPushButton(self.frame_2)
        self.analyseVideoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.analyseVideoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.analyseVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.analyseVideoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analyseVideoButton.setIcon(icon1)
        self.analyseVideoButton.setIconSize(QtCore.QSize(30, 30))
        self.analyseVideoButton.setObjectName("analyseVideoButton")
        self.verticalLayout_2.addWidget(self.analyseVideoButton)
        self.saveVideoButton = QtWidgets.QPushButton(self.frame_2)
        self.saveVideoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.saveVideoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.saveVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.saveVideoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveVideoButton.setIcon(icon2)
        self.saveVideoButton.setIconSize(QtCore.QSize(30, 30))
        self.saveVideoButton.setObjectName("saveVideoButton")
        self.verticalLayout_2.addWidget(self.saveVideoButton)
        self.deleteVideoButton = QtWidgets.QPushButton(self.frame_2)
        self.deleteVideoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.deleteVideoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.deleteVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.deleteVideoButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteVideoButton.setIcon(icon3)
        self.deleteVideoButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteVideoButton.setObjectName("deleteVideoButton")
        self.verticalLayout_2.addWidget(self.deleteVideoButton)
        self.gridLayout_10.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.currentVideoGroupBox, 1, 0, 1, 1)
        self.videoDateGroupBox = QtWidgets.QGroupBox(self.videoGalleryPage)
        self.videoDateGroupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.videoDateGroupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.videoDateGroupBox.setFont(font)
        self.videoDateGroupBox.setStyleSheet("background-color: #333333;\n"
"border: 1px solid #333333;\n"
"border-top: 10px solid #333333;")
        self.videoDateGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.videoDateGroupBox.setFlat(False)
        self.videoDateGroupBox.setObjectName("videoDateGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.videoDateGroupBox)
        self.gridLayout_9.setContentsMargins(2, 9, 2, 2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.videosDateListWidget = QtWidgets.QListWidget(self.videoDateGroupBox)
        self.videosDateListWidget.setMinimumSize(QtCore.QSize(110, 0))
        self.videosDateListWidget.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.videosDateListWidget.setFont(font)
        self.videosDateListWidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(46, 52, 54);")
        self.videosDateListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videosDateListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.videosDateListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.videosDateListWidget.setAlternatingRowColors(False)
        self.videosDateListWidget.setGridSize(QtCore.QSize(110, 25))
        self.videosDateListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.videosDateListWidget.setUniformItemSizes(True)
        self.videosDateListWidget.setWordWrap(True)
        self.videosDateListWidget.setSelectionRectVisible(True)
        self.videosDateListWidget.setObjectName("videosDateListWidget")
        self.gridLayout_9.addWidget(self.videosDateListWidget, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.videoDateGroupBox)
        self.line_2.setMinimumSize(QtCore.QSize(0, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 5, 0, 1, 1)
        self.deleteAllVideosButton = QtWidgets.QPushButton(self.videoDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteAllVideosButton.setFont(font)
        self.deleteAllVideosButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/delete_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAllVideosButton.setIcon(icon4)
        self.deleteAllVideosButton.setObjectName("deleteAllVideosButton")
        self.gridLayout_9.addWidget(self.deleteAllVideosButton, 9, 0, 1, 1)
        self.deleteDateVideosButton = QtWidgets.QPushButton(self.videoDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteDateVideosButton.setFont(font)
        self.deleteDateVideosButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.deleteDateVideosButton.setIcon(icon3)
        self.deleteDateVideosButton.setObjectName("deleteDateVideosButton")
        self.gridLayout_9.addWidget(self.deleteDateVideosButton, 7, 0, 1, 1)
        self.selectVideoDateEdit = QtWidgets.QDateEdit(self.videoDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectVideoDateEdit.setFont(font)
        self.selectVideoDateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #262626;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}")
        self.selectVideoDateEdit.setFrame(True)
        self.selectVideoDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.selectVideoDateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.selectVideoDateEdit.setProperty("showGroupSeparator", False)
        self.selectVideoDateEdit.setCalendarPopup(True)
        self.selectVideoDateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.selectVideoDateEdit.setDate(QtCore.QDate(2016, 4, 11))
        self.selectVideoDateEdit.setObjectName("selectVideoDateEdit")
        self.gridLayout_9.addWidget(self.selectVideoDateEdit, 3, 0, 1, 1)
        self.refreshVideosButton = QtWidgets.QPushButton(self.videoDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.refreshVideosButton.setFont(font)
        self.refreshVideosButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshVideosButton.setIcon(icon5)
        self.refreshVideosButton.setObjectName("refreshVideosButton")
        self.gridLayout_9.addWidget(self.refreshVideosButton, 6, 0, 1, 1)
        self.gridLayout_13.addWidget(self.videoDateGroupBox, 1, 1, 2, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.videoGalleryPage)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 130))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.scrollArea_2.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 768, 132))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.previousVideoButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.previousVideoButton.setMinimumSize(QtCore.QSize(10, 130))
        self.previousVideoButton.setMaximumSize(QtCore.QSize(30, 130))
        self.previousVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.previousVideoButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/arrow_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousVideoButton.setIcon(icon6)
        self.previousVideoButton.setObjectName("previousVideoButton")
        self.gridLayout_12.addWidget(self.previousVideoButton, 0, 0, 1, 1)
        self.nextVideoButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.nextVideoButton.setMinimumSize(QtCore.QSize(30, 130))
        self.nextVideoButton.setMaximumSize(QtCore.QSize(30, 130))
        self.nextVideoButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.nextVideoButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextVideoButton.setIcon(icon7)
        self.nextVideoButton.setObjectName("nextVideoButton")
        self.gridLayout_12.addWidget(self.nextVideoButton, 0, 2, 1, 1)
        self.videosListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.videosListWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.videosListWidget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.videosListWidget.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.videosListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.videosListWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videosListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.videosListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.videosListWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.videosListWidget.setTabKeyNavigation(True)
        self.videosListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.videosListWidget.setAlternatingRowColors(True)
        self.videosListWidget.setIconSize(QtCore.QSize(100, 140))
        self.videosListWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.videosListWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.videosListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.videosListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.videosListWidget.setGridSize(QtCore.QSize(150, 150))
        self.videosListWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.videosListWidget.setUniformItemSizes(True)
        self.videosListWidget.setObjectName("videosListWidget")
        self.gridLayout_12.addWidget(self.videosListWidget, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_13.addWidget(self.scrollArea_2, 2, 0, 1, 1)
        self.videoGalleryTitleLabel = QtWidgets.QLabel(self.videoGalleryPage)
        self.videoGalleryTitleLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.videoGalleryTitleLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.videoGalleryTitleLabel.setFont(font)
        self.videoGalleryTitleLabel.setStyleSheet("background-color: #262626;\n"
"color: rgb(115, 210, 22);")
        self.videoGalleryTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoGalleryTitleLabel.setObjectName("videoGalleryTitleLabel")
        self.gridLayout_13.addWidget(self.videoGalleryTitleLabel, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.videoGalleryPage)
        self.snapshotGalleryPage = QtWidgets.QWidget()
        self.snapshotGalleryPage.setObjectName("snapshotGalleryPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.snapshotGalleryPage)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.snapshotGalleryPage)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 130))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 130))
        self.scrollArea.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 768, 132))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.previousImageButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.previousImageButton.setMinimumSize(QtCore.QSize(10, 130))
        self.previousImageButton.setMaximumSize(QtCore.QSize(30, 130))
        self.previousImageButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.previousImageButton.setText("")
        self.previousImageButton.setIcon(icon6)
        self.previousImageButton.setObjectName("previousImageButton")
        self.gridLayout_6.addWidget(self.previousImageButton, 0, 0, 1, 1)
        self.nextImageButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.nextImageButton.setMinimumSize(QtCore.QSize(30, 130))
        self.nextImageButton.setMaximumSize(QtCore.QSize(30, 130))
        self.nextImageButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.nextImageButton.setText("")
        self.nextImageButton.setIcon(icon7)
        self.nextImageButton.setObjectName("nextImageButton")
        self.gridLayout_6.addWidget(self.nextImageButton, 0, 2, 1, 1)
        self.imagesListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.imagesListWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.imagesListWidget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.imagesListWidget.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.imagesListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.imagesListWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imagesListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imagesListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imagesListWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.imagesListWidget.setTabKeyNavigation(True)
        self.imagesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.imagesListWidget.setAlternatingRowColors(True)
        self.imagesListWidget.setIconSize(QtCore.QSize(100, 140))
        self.imagesListWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.imagesListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.imagesListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.imagesListWidget.setGridSize(QtCore.QSize(150, 150))
        self.imagesListWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.imagesListWidget.setUniformItemSizes(True)
        self.imagesListWidget.setObjectName("imagesListWidget")
        self.gridLayout_6.addWidget(self.imagesListWidget, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.currentImageGroupBox = QtWidgets.QGroupBox(self.snapshotGalleryPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.currentImageGroupBox.setFont(font)
        self.currentImageGroupBox.setStyleSheet("background-color: #333333;\n"
"border: 1px solid #333333;\n"
"border-top: 10px solid #333333;")
        self.currentImageGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.currentImageGroupBox.setObjectName("currentImageGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.currentImageGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 3, 1, 1)
        self.currentImageLabel = QtWidgets.QLabel(self.currentImageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentImageLabel.sizePolicy().hasHeightForWidth())
        self.currentImageLabel.setSizePolicy(sizePolicy)
        self.currentImageLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.currentImageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.currentImageLabel.setStyleSheet("background-color: #333333;")
        self.currentImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.currentImageLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentImageLabel.setText("")
        self.currentImageLabel.setScaledContents(True)
        self.currentImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentImageLabel.setWordWrap(False)
        self.currentImageLabel.setObjectName("currentImageLabel")
        self.gridLayout_5.addWidget(self.currentImageLabel, 0, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.currentImageGroupBox)
        self.frame_3.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.saveSnapshotButton = QtWidgets.QPushButton(self.frame_3)
        self.saveSnapshotButton.setMinimumSize(QtCore.QSize(40, 40))
        self.saveSnapshotButton.setMaximumSize(QtCore.QSize(40, 40))
        self.saveSnapshotButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.saveSnapshotButton.setText("")
        self.saveSnapshotButton.setIcon(icon2)
        self.saveSnapshotButton.setIconSize(QtCore.QSize(30, 30))
        self.saveSnapshotButton.setObjectName("saveSnapshotButton")
        self.verticalLayout_3.addWidget(self.saveSnapshotButton)
        self.deleteSnapshotButton = QtWidgets.QPushButton(self.frame_3)
        self.deleteSnapshotButton.setMinimumSize(QtCore.QSize(40, 40))
        self.deleteSnapshotButton.setMaximumSize(QtCore.QSize(40, 40))
        self.deleteSnapshotButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.deleteSnapshotButton.setText("")
        self.deleteSnapshotButton.setIcon(icon3)
        self.deleteSnapshotButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteSnapshotButton.setObjectName("deleteSnapshotButton")
        self.verticalLayout_3.addWidget(self.deleteSnapshotButton)
        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.currentImageGroupBox, 1, 0, 1, 1)
        self.imageDateGroupBox = QtWidgets.QGroupBox(self.snapshotGalleryPage)
        self.imageDateGroupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.imageDateGroupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.imageDateGroupBox.setFont(font)
        self.imageDateGroupBox.setStyleSheet("background-color: #333333;\n"
"border: 1px solid #333333;\n"
"border-top: 10px solid #333333;")
        self.imageDateGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.imageDateGroupBox.setObjectName("imageDateGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.imageDateGroupBox)
        self.gridLayout_8.setContentsMargins(2, 9, 2, 2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.deleteAllSnapshotsButton = QtWidgets.QPushButton(self.imageDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteAllSnapshotsButton.setFont(font)
        self.deleteAllSnapshotsButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.deleteAllSnapshotsButton.setIcon(icon4)
        self.deleteAllSnapshotsButton.setObjectName("deleteAllSnapshotsButton")
        self.gridLayout_8.addWidget(self.deleteAllSnapshotsButton, 8, 0, 1, 1)
        self.refreshSnapshotsButton = QtWidgets.QPushButton(self.imageDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.refreshSnapshotsButton.setFont(font)
        self.refreshSnapshotsButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.refreshSnapshotsButton.setIcon(icon5)
        self.refreshSnapshotsButton.setAutoDefault(False)
        self.refreshSnapshotsButton.setDefault(False)
        self.refreshSnapshotsButton.setObjectName("refreshSnapshotsButton")
        self.gridLayout_8.addWidget(self.refreshSnapshotsButton, 6, 0, 1, 1)
        self.imagesDateListWidget = QtWidgets.QListWidget(self.imageDateGroupBox)
        self.imagesDateListWidget.setMinimumSize(QtCore.QSize(110, 0))
        self.imagesDateListWidget.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.imagesDateListWidget.setFont(font)
        self.imagesDateListWidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(46, 52, 54);")
        self.imagesDateListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imagesDateListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imagesDateListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imagesDateListWidget.setAlternatingRowColors(False)
        self.imagesDateListWidget.setGridSize(QtCore.QSize(110, 25))
        self.imagesDateListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.imagesDateListWidget.setUniformItemSizes(True)
        self.imagesDateListWidget.setWordWrap(True)
        self.imagesDateListWidget.setSelectionRectVisible(True)
        self.imagesDateListWidget.setObjectName("imagesDateListWidget")
        self.gridLayout_8.addWidget(self.imagesDateListWidget, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.selectImageDateEdit = QtWidgets.QDateEdit(self.imageDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectImageDateEdit.setFont(font)
        self.selectImageDateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #262626;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}")
        self.selectImageDateEdit.setFrame(True)
        self.selectImageDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.selectImageDateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.selectImageDateEdit.setProperty("showGroupSeparator", False)
        self.selectImageDateEdit.setCalendarPopup(True)
        self.selectImageDateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.selectImageDateEdit.setDate(QtCore.QDate(2016, 4, 11))
        self.selectImageDateEdit.setObjectName("selectImageDateEdit")
        self.gridLayout_8.addWidget(self.selectImageDateEdit, 3, 0, 1, 1)
        self.deleteDateSnapshotsButton = QtWidgets.QPushButton(self.imageDateGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteDateSnapshotsButton.setFont(font)
        self.deleteDateSnapshotsButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.deleteDateSnapshotsButton.setIcon(icon3)
        self.deleteDateSnapshotsButton.setObjectName("deleteDateSnapshotsButton")
        self.gridLayout_8.addWidget(self.deleteDateSnapshotsButton, 7, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.imageDateGroupBox)
        self.line_3.setMinimumSize(QtCore.QSize(0, 5))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 5, 0, 1, 1)
        self.gridLayout_4.addWidget(self.imageDateGroupBox, 1, 1, 2, 1)
        self.snapshotGalleryTitleLabel = QtWidgets.QLabel(self.snapshotGalleryPage)
        self.snapshotGalleryTitleLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.snapshotGalleryTitleLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.snapshotGalleryTitleLabel.setFont(font)
        self.snapshotGalleryTitleLabel.setStyleSheet("background-color: #262626;\n"
"color: rgb(115, 210, 22);")
        self.snapshotGalleryTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.snapshotGalleryTitleLabel.setObjectName("snapshotGalleryTitleLabel")
        self.gridLayout_4.addWidget(self.snapshotGalleryTitleLabel, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.snapshotGalleryPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBar.setStyleSheet("QToolBar {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#101010;\n"
"}\n"
"\n"
"QToolBar::handle {\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    background-color:orange;\n"
"}\n"
"\n"
"QToolBar QToolButton {\n"
"    background-color:#101010;\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    border: 5px solid  #101010;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"}\n"
"\n"
"QToolBar QToolButton::hover {\n"
"    border: 5px solid #ffff66;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-top: 0px\n"
"}\n"
"\n"
"QToolBar QToolButton::checked {\n"
"    border: 5px solid #ffff66;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"}")
        self.toolBar.setMovable(True)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBar_2.setStyleSheet("QToolBar {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#101010;\n"
"}\n"
"\n"
"QToolBar::handle {\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    background-color:orange;\n"
"}\n"
"\n"
"QToolBar QToolButton {\n"
"    background-color:#101010;\n"
"    height: 60px;\n"
"    width: 60px;\n"
"    border: 5px solid  #101010;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"}\n"
"\n"
"QToolBar QToolButton::hover {\n"
"    border: 5px solid #ffff66;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-top: 0px\n"
"}\n"
"\n"
"QToolBar QToolButton::checked {\n"
"    border: 5px solid #ffff66;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"}")
        self.toolBar_2.setMovable(True)
        self.toolBar_2.setIconSize(QtCore.QSize(30, 30))
        self.toolBar_2.setFloatable(False)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar_2)
        self.actionCascade_View = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/cascade_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCascade_View.setIcon(icon8)
        self.actionCascade_View.setObjectName("actionCascade_View")
        self.actionTiled_View = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/tiled_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTiled_View.setIcon(icon9)
        self.actionTiled_View.setObjectName("actionTiled_View")
        self.actionStop_All_Streams = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_All_Streams.setIcon(icon10)
        self.actionStop_All_Streams.setObjectName("actionStop_All_Streams")
        self.actionStart_All_Streams = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/start_all_cameras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_All_Streams.setIcon(icon11)
        self.actionStart_All_Streams.setObjectName("actionStart_All_Streams")
        self.actionSurveillance_Mode = QtWidgets.QAction(MainWindow)
        self.actionSurveillance_Mode.setCheckable(True)
        self.actionSurveillance_Mode.setChecked(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/basic_video.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSurveillance_Mode.setIcon(icon12)
        self.actionSurveillance_Mode.setObjectName("actionSurveillance_Mode")
        self.actionAdd_Stream = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/add_camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Stream.setIcon(icon13)
        self.actionAdd_Stream.setObjectName("actionAdd_Stream")
        self.actionSnapshot_Gallery = QtWidgets.QAction(MainWindow)
        self.actionSnapshot_Gallery.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/basic_picture.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSnapshot_Gallery.setIcon(icon14)
        self.actionSnapshot_Gallery.setObjectName("actionSnapshot_Gallery")
        self.actionVideo_Gallery = QtWidgets.QAction(MainWindow)
        self.actionVideo_Gallery.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/video_film_strip.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVideo_Gallery.setIcon(icon15)
        self.actionVideo_Gallery.setObjectName("actionVideo_Gallery")
        self.actionSave_All_Videos = QtWidgets.QAction(MainWindow)
        self.actionSave_All_Videos.setCheckable(True)
        self.actionSave_All_Videos.setIcon(icon2)
        self.actionSave_All_Videos.setObjectName("actionSave_All_Videos")
        self.actionAll_People_Counters = QtWidgets.QAction(MainWindow)
        self.actionAll_People_Counters.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/all_facial_recognitions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAll_People_Counters.setIcon(icon16)
        self.actionAll_People_Counters.setObjectName("actionAll_People_Counters")
        self.actionAll_Snapshots = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/take_all_snapshots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAll_Snapshots.setIcon(icon17)
        self.actionAll_Snapshots.setObjectName("actionAll_Snapshots")
        self.actionAll_Colored_Modes = QtWidgets.QAction(MainWindow)
        self.actionAll_Colored_Modes.setCheckable(True)
        self.actionAll_Colored_Modes.setChecked(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/all_colored_modes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAll_Colored_Modes.setIcon(icon18)
        self.actionAll_Colored_Modes.setObjectName("actionAll_Colored_Modes")
        self.actionHide_All_Video_Menus = QtWidgets.QAction(MainWindow)
        self.actionHide_All_Video_Menus.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/hide_all_vid_menus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_All_Video_Menus.setIcon(icon19)
        self.actionHide_All_Video_Menus.setObjectName("actionHide_All_Video_Menus")
        self.actionEmbed_Time_For_All_Videos = QtWidgets.QAction(MainWindow)
        self.actionEmbed_Time_For_All_Videos.setCheckable(True)
        self.actionEmbed_Time_For_All_Videos.setChecked(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icons/embed_time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmbed_Time_For_All_Videos.setIcon(icon20)
        self.actionEmbed_Time_For_All_Videos.setObjectName("actionEmbed_Time_For_All_Videos")
        self.toolBar.addAction(self.actionAdd_Stream)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart_All_Streams)
        self.toolBar.addAction(self.actionStop_All_Streams)
        self.toolBar.addAction(self.actionEmbed_Time_For_All_Videos)
        self.toolBar.addAction(self.actionSave_All_Videos)
        self.toolBar.addAction(self.actionAll_People_Counters)
        self.toolBar.addAction(self.actionAll_Colored_Modes)
        self.toolBar.addAction(self.actionAll_Snapshots)
        self.toolBar.addAction(self.actionHide_All_Video_Menus)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCascade_View)
        self.toolBar.addAction(self.actionTiled_View)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar_2.addAction(self.actionSurveillance_Mode)
        self.toolBar_2.addAction(self.actionVideo_Gallery)
        self.toolBar_2.addAction(self.actionSnapshot_Gallery)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.imagesListWidget, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.previousImageButton)
        MainWindow.setTabOrder(self.previousImageButton, self.nextImageButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentVideoGroupBox.setTitle(_translate("MainWindow", "FILE INFORMATION"))
        self.currentVideoLabel.setToolTip(_translate("MainWindow", "Double click to play the video"))
        self.playVideoButton.setToolTip(_translate("MainWindow", "Play Selected Video"))
        self.analyseVideoButton.setToolTip(_translate("MainWindow", "Load Selected Video For Analysis"))
        self.saveVideoButton.setToolTip(_translate("MainWindow", "Save Copy Of Selected Video"))
        self.deleteVideoButton.setToolTip(_translate("MainWindow", "Delete Selected Video"))
        self.videoDateGroupBox.setTitle(_translate("MainWindow", "DATE"))
        self.deleteAllVideosButton.setToolTip(_translate("MainWindow", "Delete All Videos"))
        self.deleteAllVideosButton.setText(_translate("MainWindow", "Delete All"))
        self.deleteDateVideosButton.setToolTip(_translate("MainWindow", "Delete All Videos For The Selected Date"))
        self.deleteDateVideosButton.setText(_translate("MainWindow", "Delete Date"))
        self.selectVideoDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.refreshVideosButton.setToolTip(_translate("MainWindow", "Refresh"))
        self.refreshVideosButton.setText(_translate("MainWindow", "Refresh"))
        self.previousVideoButton.setToolTip(_translate("MainWindow", "Back"))
        self.nextVideoButton.setToolTip(_translate("MainWindow", "Next"))
        self.videosListWidget.setToolTip(_translate("MainWindow", "Press delete to delete selected video"))
        self.videoGalleryTitleLabel.setText(_translate("MainWindow", "VIDEO GALLERY"))
        self.previousImageButton.setToolTip(_translate("MainWindow", "Back"))
        self.nextImageButton.setToolTip(_translate("MainWindow", "Next"))
        self.imagesListWidget.setToolTip(_translate("MainWindow", "Press delete to delete selected image"))
        self.currentImageGroupBox.setTitle(_translate("MainWindow", "FILE INFORMATION"))
        self.currentImageLabel.setToolTip(_translate("MainWindow", "Double click to save a copy of the image"))
        self.saveSnapshotButton.setToolTip(_translate("MainWindow", "Save Copy Of Selected Image"))
        self.deleteSnapshotButton.setToolTip(_translate("MainWindow", "Delete Selected Image"))
        self.imageDateGroupBox.setTitle(_translate("MainWindow", "DATE"))
        self.deleteAllSnapshotsButton.setToolTip(_translate("MainWindow", "Delete All Snapshots"))
        self.deleteAllSnapshotsButton.setText(_translate("MainWindow", "Delete All"))
        self.refreshSnapshotsButton.setToolTip(_translate("MainWindow", "Refresh"))
        self.refreshSnapshotsButton.setText(_translate("MainWindow", "Refresh"))
        self.selectImageDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.deleteDateSnapshotsButton.setToolTip(_translate("MainWindow", "Delete All Snapshots For The Selected Date"))
        self.deleteDateSnapshotsButton.setText(_translate("MainWindow", "Delete Date"))
        self.snapshotGalleryTitleLabel.setText(_translate("MainWindow", "SNAPSHOT GALLERY"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionCascade_View.setText(_translate("MainWindow", "Cascade View "))
        self.actionCascade_View.setToolTip(_translate("MainWindow", "Cascade Window View (Ctrl + C)"))
        self.actionCascade_View.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionTiled_View.setText(_translate("MainWindow", "Tiled View "))
        self.actionTiled_View.setToolTip(_translate("MainWindow", "Tile Window View (Ctrl + T)"))
        self.actionTiled_View.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionStop_All_Streams.setText(_translate("MainWindow", "Stop All Streams "))
        self.actionStop_All_Streams.setToolTip(_translate("MainWindow", "Stop All Streams (Ctrl + Alt + X)"))
        self.actionStop_All_Streams.setShortcut(_translate("MainWindow", "Ctrl+Alt+X"))
        self.actionStart_All_Streams.setText(_translate("MainWindow", "Start All Streams "))
        self.actionStart_All_Streams.setToolTip(_translate("MainWindow", "Start All Streams (Ctrl + Alt + B)"))
        self.actionStart_All_Streams.setShortcut(_translate("MainWindow", "Ctrl+Alt+B"))
        self.actionSurveillance_Mode.setText(_translate("MainWindow", "Surveillance Mode "))
        self.actionSurveillance_Mode.setToolTip(_translate("MainWindow", "Switch To Surveillance Mode (Shift + V)"))
        self.actionSurveillance_Mode.setShortcut(_translate("MainWindow", "Shift+V"))
        self.actionAdd_Stream.setText(_translate("MainWindow", "Add Stream"))
        self.actionAdd_Stream.setToolTip(_translate("MainWindow", "Add New Stream (Ctrl + A)"))
        self.actionAdd_Stream.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionSnapshot_Gallery.setText(_translate("MainWindow", "Snapshot Gallery"))
        self.actionSnapshot_Gallery.setToolTip(_translate("MainWindow", "View Snapshot Gallery (Shift + G)"))
        self.actionSnapshot_Gallery.setShortcut(_translate("MainWindow", "Shift+G"))
        self.actionVideo_Gallery.setText(_translate("MainWindow", "Video Gallery"))
        self.actionVideo_Gallery.setToolTip(_translate("MainWindow", "Switch to Video Gallery (Shift + K)"))
        self.actionVideo_Gallery.setShortcut(_translate("MainWindow", "Shift+K"))
        self.actionSave_All_Videos.setText(_translate("MainWindow", "Save All Videos"))
        self.actionSave_All_Videos.setToolTip(_translate("MainWindow", "Save all video streams (Alt + D)"))
        self.actionSave_All_Videos.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actionAll_People_Counters.setText(_translate("MainWindow", "All People Counters"))
        self.actionAll_People_Counters.setIconText(_translate("MainWindow", "All People Counters"))
        self.actionAll_People_Counters.setToolTip(_translate("MainWindow", "Enable All People Counters (Alt + F)"))
        self.actionAll_People_Counters.setShortcut(_translate("MainWindow", "Alt+F"))
        self.actionAll_Snapshots.setText(_translate("MainWindow", "All Snapshots"))
        self.actionAll_Snapshots.setToolTip(_translate("MainWindow", "Take Snapshot For All Video Streams (Alt + S)"))
        self.actionAll_Snapshots.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionAll_Colored_Modes.setText(_translate("MainWindow", "All Colored Modes"))
        self.actionAll_Colored_Modes.setToolTip(_translate("MainWindow", "Toggle Colored Or Grayscale Modes For All Streams (Alt + C) "))
        self.actionAll_Colored_Modes.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionHide_All_Video_Menus.setText(_translate("MainWindow", "Hide All Video Menus"))
        self.actionHide_All_Video_Menus.setToolTip(_translate("MainWindow", "Hide/Show Video Menus (Alt + H)"))
        self.actionHide_All_Video_Menus.setShortcut(_translate("MainWindow", "Alt+H"))
        self.actionEmbed_Time_For_All_Videos.setText(_translate("MainWindow", "Embed Time For All Videos"))
        self.actionEmbed_Time_For_All_Videos.setToolTip(_translate("MainWindow", "Embed/Exclude Time For All Videos (Alt + T)"))
        self.actionEmbed_Time_For_All_Videos.setShortcut(_translate("MainWindow", "Alt+T"))
