# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdi_content.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mdiSubWIndowContent(object):
    def setupUi(self, mdiSubWIndowContent):
        mdiSubWIndowContent.setObjectName("mdiSubWIndowContent")
        mdiSubWIndowContent.resize(555, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/alpha_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mdiSubWIndowContent.setWindowIcon(icon)
        mdiSubWIndowContent.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(mdiSubWIndowContent)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.displayLabel = QtWidgets.QLabel(mdiSubWIndowContent)
        self.displayLabel.setStyleSheet("background-color: #101010;")
        self.displayLabel.setText("")
        self.displayLabel.setScaledContents(True)
        self.displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayLabel.setObjectName("displayLabel")
        self.gridLayout.addWidget(self.displayLabel, 1, 0, 1, 1)
        self.sourceIdLabel = QtWidgets.QLabel(mdiSubWIndowContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceIdLabel.sizePolicy().hasHeightForWidth())
        self.sourceIdLabel.setSizePolicy(sizePolicy)
        self.sourceIdLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.sourceIdLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sourceIdLabel.setFont(font)
        self.sourceIdLabel.setStyleSheet("background-color: #333333;")
        self.sourceIdLabel.setScaledContents(True)
        self.sourceIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceIdLabel.setObjectName("sourceIdLabel")
        self.gridLayout.addWidget(self.sourceIdLabel, 0, 0, 1, 1)
        self.optionsScrollArea = QtWidgets.QScrollArea(mdiSubWIndowContent)
        self.optionsScrollArea.setMinimumSize(QtCore.QSize(55, 0))
        self.optionsScrollArea.setMaximumSize(QtCore.QSize(55, 16777215))
        self.optionsScrollArea.setStyleSheet("background-color: #333333;")
        self.optionsScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.optionsScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.optionsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.optionsScrollArea.setWidgetResizable(True)
        self.optionsScrollArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.optionsScrollArea.setObjectName("optionsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(5, 0, 50, 477))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(40, 260))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(50, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.optionsFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsFrame.sizePolicy().hasHeightForWidth())
        self.optionsFrame.setSizePolicy(sizePolicy)
        self.optionsFrame.setMinimumSize(QtCore.QSize(40, 0))
        self.optionsFrame.setMaximumSize(QtCore.QSize(45, 16777215))
        self.optionsFrame.setStyleSheet("background-color: #333333;")
        self.optionsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.optionsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.optionsFrame.setObjectName("optionsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.optionsFrame)
        self.verticalLayout.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.closeButton = QtWidgets.QPushButton(self.optionsFrame)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 25))
        self.closeButton.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.line_6 = QtWidgets.QFrame(self.optionsFrame)
        self.line_6.setMinimumSize(QtCore.QSize(0, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.embedTimeCheckBox = QtWidgets.QCheckBox(self.optionsFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.embedTimeCheckBox.setFont(font)
        self.embedTimeCheckBox.setStyleSheet("QCheckBox {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    background-color: #ffffff;\n"
"    color: #262626;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(115, 210, 22);\n"
"}")
        self.embedTimeCheckBox.setChecked(True)
        self.embedTimeCheckBox.setObjectName("embedTimeCheckBox")
        self.verticalLayout.addWidget(self.embedTimeCheckBox)
        self.line_5 = QtWidgets.QFrame(self.optionsFrame)
        self.line_5.setStyleSheet("background-color: #333333;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.saveVideoCheckBox = QtWidgets.QCheckBox(self.optionsFrame)
        self.saveVideoCheckBox.setMinimumSize(QtCore.QSize(15, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.saveVideoCheckBox.setFont(font)
        self.saveVideoCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveVideoCheckBox.setStyleSheet("QCheckBox {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    background-color: #ffffff;\n"
"    color: #262626;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(115, 210, 22);\n"
"}")
        self.saveVideoCheckBox.setObjectName("saveVideoCheckBox")
        self.verticalLayout.addWidget(self.saveVideoCheckBox)
        self.line_2 = QtWidgets.QFrame(self.optionsFrame)
        self.line_2.setStyleSheet("background-color: #333333;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.peopleCounterCheckbox = QtWidgets.QCheckBox(self.optionsFrame)
        self.peopleCounterCheckbox.setMinimumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.peopleCounterCheckbox.setFont(font)
        self.peopleCounterCheckbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.peopleCounterCheckbox.setStyleSheet("QCheckBox {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    background-color: #ffffff;\n"
"    color: #262626;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(115, 210, 22);\n"
"}")
        self.peopleCounterCheckbox.setObjectName("peopleCounterCheckbox")
        self.verticalLayout.addWidget(self.peopleCounterCheckbox)
        self.line = QtWidgets.QFrame(self.optionsFrame)
        self.line.setStyleSheet("background-color: #333333;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.grayscaleRadioButton = QtWidgets.QRadioButton(self.optionsFrame)
        self.grayscaleRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.grayscaleRadioButton.setFont(font)
        self.grayscaleRadioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.grayscaleRadioButton.setStyleSheet("QRadioButton {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    background-color: #ffffff;\n"
"    color: #262626;\n"
"    border-radius: 5px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(115, 210, 22);\n"
"}")
        self.grayscaleRadioButton.setObjectName("grayscaleRadioButton")
        self.verticalLayout.addWidget(self.grayscaleRadioButton)
        self.coloredRadioButton = QtWidgets.QRadioButton(self.optionsFrame)
        self.coloredRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.coloredRadioButton.setFont(font)
        self.coloredRadioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coloredRadioButton.setStyleSheet("QRadioButton {\n"
"    background-color: #333333;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    background-color: #ffffff;\n"
"    color: #262626;\n"
"    border-radius: 5px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(115, 210, 22);\n"
"}")
        self.coloredRadioButton.setChecked(True)
        self.coloredRadioButton.setObjectName("coloredRadioButton")
        self.verticalLayout.addWidget(self.coloredRadioButton)
        self.line_3 = QtWidgets.QFrame(self.optionsFrame)
        self.line_3.setStyleSheet("background-color: #333333;")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.startButton = QtWidgets.QPushButton(self.optionsFrame)
        self.startButton.setMinimumSize(QtCore.QSize(0, 20))
        self.startButton.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.endButton = QtWidgets.QPushButton(self.optionsFrame)
        self.endButton.setMinimumSize(QtCore.QSize(0, 20))
        self.endButton.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.endButton.setFont(font)
        self.endButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.endButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.endButton.setObjectName("endButton")
        self.verticalLayout.addWidget(self.endButton)
        self.line_4 = QtWidgets.QFrame(self.optionsFrame)
        self.line_4.setStyleSheet("background-color: #333333;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.snapshotButton = QtWidgets.QPushButton(self.optionsFrame)
        self.snapshotButton.setMinimumSize(QtCore.QSize(0, 20))
        self.snapshotButton.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.snapshotButton.setFont(font)
        self.snapshotButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.snapshotButton.setStyleSheet("QPushButton {\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #888888;\n"
"    color: #262626;\n"
"}")
        self.snapshotButton.setObjectName("snapshotButton")
        self.verticalLayout.addWidget(self.snapshotButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.optionsFrame, 0, 0, 1, 1)
        self.optionsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.optionsScrollArea, 0, 1, 2, 1)

        self.retranslateUi(mdiSubWIndowContent)
        self.closeButton.clicked.connect(mdiSubWIndowContent.close)
        QtCore.QMetaObject.connectSlotsByName(mdiSubWIndowContent)

    def retranslateUi(self, mdiSubWIndowContent):
        _translate = QtCore.QCoreApplication.translate
        mdiSubWIndowContent.setWindowTitle(_translate("mdiSubWIndowContent", "Form"))
        self.sourceIdLabel.setText(_translate("mdiSubWIndowContent", "SOURCE ID"))
        self.closeButton.setText(_translate("mdiSubWIndowContent", "Exit"))
        self.embedTimeCheckBox.setToolTip(_translate("mdiSubWIndowContent", "Hide/Show Time In Video Frames"))
        self.embedTimeCheckBox.setText(_translate("mdiSubWIndowContent", "T"))
        self.saveVideoCheckBox.setToolTip(_translate("mdiSubWIndowContent", "Save video stream to file"))
        self.saveVideoCheckBox.setText(_translate("mdiSubWIndowContent", "S"))
        self.peopleCounterCheckbox.setToolTip(_translate("mdiSubWIndowContent", "Activate people counter"))
        self.peopleCounterCheckbox.setText(_translate("mdiSubWIndowContent", "D"))
        self.grayscaleRadioButton.setToolTip(_translate("mdiSubWIndowContent", "Display grayscale video"))
        self.grayscaleRadioButton.setText(_translate("mdiSubWIndowContent", "G"))
        self.coloredRadioButton.setToolTip(_translate("mdiSubWIndowContent", "Display colored video"))
        self.coloredRadioButton.setText(_translate("mdiSubWIndowContent", "C"))
        self.startButton.setToolTip(_translate("mdiSubWIndowContent", "Start video stream"))
        self.startButton.setText(_translate("mdiSubWIndowContent", "ST"))
        self.endButton.setToolTip(_translate("mdiSubWIndowContent", "End video stream"))
        self.endButton.setText(_translate("mdiSubWIndowContent", "EN"))
        self.snapshotButton.setToolTip(_translate("mdiSubWIndowContent", "Take snapshot"))
        self.snapshotButton.setText(_translate("mdiSubWIndowContent", "SN"))
